apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-service-deployment-2
  labels:
    app: api-server-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server-svc-2
  template:
    metadata:
      labels:
        app: api-server-svc-2
    spec:
      containers:
      - name: api-server-svc-2
        image: appvillisdocker/api-server-2:prod-{{ .Values.tag }}
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: regcred