apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: api-service-2
spec:
  rules:
  - host: nice.esimplus.mobi
    http:
      paths:
      - backend:
          service:
            name: api-server-svc-service-2
            port:
              number: 8882
        path: /api-service-2/(.*)
        pathType: Prefix