apiVersion: apps/v1
kind: Deployment
metadata:
  name: goroutine-service-deployment
  labels:
    app: goroutine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goroutine-svc
  template:
    metadata:
      labels:
        app: goroutine-svc
    spec:
      containers:
      - name: goroutine-svc
        image: appvillisdocker/goroutine-server:prod-{{ .Values.tag }}
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: regcred