apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-server-service-deployment
  labels:
    app: root-server-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: root-server-svc
  template:
    metadata:
      labels:
        app: root-server-svc
    spec:
      containers:
      - name: root-server-svc
        image: appvillisdocker/root-server:prod-{{ .Values.tag }}
        ports:
        - containerPort: 80
        
      imagePullSecrets:
      - name: regcred