apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: root-service
spec:
  rules:
  - host: nice.esimplus.mobi
    http:
      paths:
      - backend:
          service:
            name: root-server-svc-service
            port:
              number: 8882
        path: /root-service/(.*)
        pathType: Prefix